# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Pierre Allard
title: Sports Science and Performance Director
email: allardtraining23@gmail.com
phone: 438-882-5341
website: www.github.com/sproogen/resume-theme


darkmode: false

# Social links
researchgate_username: Pierre_Allard8
github_username:  pallard23
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: pierre-allard-a5393a139
# pinterest_username: jekyll
youtube_username: UCCzA75FqSlaqH8B0b1Gl_Tg
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pierre Allard I'am in my tenth season with the Montréal Canadiens' organization (seven as a strength & conditioning coach and three as director of the sports science & performance department). I hold a Masters in Kinesiology and I'm currently a Ph.D. student at the University of Montreal, researching on External Load in Ice Hockey using IMU.

  I am most skilled in: <mark>Strength and Conditioning</mark> and <mark>Data Science</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Fishing
   - Hiking
   - Cycling
   - [Giving Webinar](https://support.catapultsports.com/hc/en-us/community/posts/360006130355-Performance-Webinar-Series-Ep-4-Pierre-Allard-Adam-Douglas-Using-Wearable-Technology-in-Ice-Hockey-April-2020-?utm_campaign=GLBL%20%7C%202020%20Performance%20Webinar%20Series&utm_source=hs_email&utm_medium=email&utm_content=86419574&_hsenc=p2ANqtz-8FRyoPryvlK5WflNFb8_I7rJGsZC5N3IzsLXfsag8ZDEndIcx9b0G-8kFPCPNBCtkZgIYpgb9LI8u5dGI4OBGO1lPmXw&_hsmi=86419574)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
